org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = neoForge

mod_version = 1.0.0
maven_group = me.kall.reminder
archives_name = reminder

minecraft_version = 1.21.1
mixinextras_version = 0.5.0

cf_project_id=""

use_shadow=false
use_mixin=false
use_mixin_extras=false
use_duplicationless=false

claim_integration=false
embeddium_integration=false